import {StyleSheet} from 'react-native';

export const globalStyles = StyleSheet.create({
  constinaer: {
    flex: 1,
    padding: 15,
  },
  loading: {
    justifyContent: 'center',
  },
  fabContainer: {
    position: 'absolute',
    bottom: 20,
    height: 80,
    width: 80,
    borderRadius: 50,
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
  },
  fab: {
    height: 70,
    width: 70,
    borderRadius: 50,
    backgroundColor: 'teal',
    justifyContent: 'center',
    alignItems: 'center',
  },
  fabContainerMain: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    height: 70,
    width: 70,
    borderRadius: 50,
    backgroundColor: 'teal',
    justifyContent: 'center',
    alignItems: 'center',
    margin: 15,
  },
  dayContainer: {
    height: 60,
    width: 90,
    backgroundColor: 'teal',
    marginHorizontal: 15,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
  },
  day: {
    height: 20,
    width: 20,
    borderRadius: 10,
    backgroundColor: 'orange',
    position: 'absolute',
    top: 0,
    right: -5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  dayText: {color: 'white', fontWeight: 'bold'},
  lessonContainer: {
    height: 150,
    width: '100%',
    marginBottom: 15,
  },
  imageContainer: {justifyContent: 'center', alignItems: 'center'},
  imageLesson: {
    height: 150,
    width: '100%',
    resizeMode: 'cover',
  },
  textLessonContainer: {position: 'absolute'},
  textLesson: {
    fontSize: 20,
    fontWeight: 'bold',
    color: 'white',
  },
  containerSchedlue: {flexDirection: 'row', justifyContent: 'center'},
  textSchedlue: {marginHorizontal: 5, color: 'white', fontSize: 17},
  textDetails: {
    fontSize: 20,
  },
  lineSeparator: {borderBottomWidth: 1, marginBottom: 5},
  schedlueDetails: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  point: {
    borderRadius: 20,
    height: 10,
    width: 10,
    backgroundColor: 'teal',
    marginRight: 15,
  },
  iconsComponentBottom: {
    position: 'absolute',
    bottom: 20,
    right: 0,
    left: 0,
    margin: 15,
  },
  iconsComponent: {flexDirection: 'row', justifyContent: 'space-evenly'},
  btnsComponent: {
    height: 70,
    width: 150,
    backgroundColor: 'teal',
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
  },
  btnsComponentText: {fontWeight: 'bold', color: 'white'},
  input: {
    height: 70,
    width: '100%',
    borderBottomWidth: 1,
    borderBottomColor: 'teal',
    fontSize: 18,
  },
  inputDesc: {
    fontSize: 18,
  },
  fabGroupVisible: {
    padding: 15,
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  fabGroupNoVisible: {padding: 15, flex: 1},
  fabGroupContainer: {
    position: 'absolute',
    bottom: 0,
    right: 0,
  },
  fabGroup3: {
    position: 'absolute',
    bottom: 90,
    right: 0,
  },
});
