export interface AuthResponse {
  token?: string;
  error?: string;
}

// Generated by https://quicktype.io

export interface SaveLessonResponse {
  lesson: Lesson;
  error?: string;
}

export interface Lesson {
  lesson: string;
  nrc: number;
  teacher: string;
  schedlue: Schedlue[];
  _id: string;
}

export interface Schedlue {
  day: string;
  hours: string;
}

export interface DeleteLessonResponse {
  error?: string;
  msg?: string;
}

export interface EditLessonResponse {
  error?: string;
  lesson: Lesson;
}
